-- Seed dream themes
-- This migration populates the themes table with common dream themes

INSERT INTO themes (code, label, description) VALUES
  -- Universal themes
  ('falling', 'Falling', 'Dreams about falling, losing balance, or dropping from heights'),
  ('flying', 'Flying', 'Dreams about flying, floating, or levitating'),
  ('being_chased', 'Being Chased', 'Dreams about being pursued or running from danger'),
  ('death', 'Death', 'Dreams about death, dying, or mortality'),
  ('lost', 'Being Lost', 'Dreams about being lost, unable to find your way'),
  ('escape', 'Escaping', 'Dreams about escaping from danger, confinement, or difficult situations'),
  ('trapped', 'Being Trapped', 'Dreams about being trapped, confined, or unable to move'),
  ('hiding', 'Hiding', 'Dreams about hiding from someone or something'),
  
  -- Relationship themes
  ('love', 'Love & Romance', 'Dreams about romantic relationships, love, or intimacy'),
  ('family', 'Family', 'Dreams involving family members or family dynamics'),
  ('friends', 'Friends', 'Dreams about friendships or social connections'),
  ('betrayal', 'Betrayal', 'Dreams about being betrayed or betraying others'),
  ('stranger', 'Strangers', 'Dreams involving unknown people or mysterious figures'),
  ('ex_partner', 'Ex-Partners', 'Dreams about former romantic partners or past relationships'),
  ('wedding', 'Wedding', 'Dreams about weddings, marriage ceremonies, or commitment'),
  ('reunion', 'Reunion', 'Dreams about reuniting with people from the past'),
  ('abandonment', 'Abandonment', 'Dreams about being abandoned or left behind'),
  ('boyfriend', 'Boyfriend', 'Dreams about boyfriends, romantic desires, or relationship dynamics'),
  ('girlfriend', 'Girlfriend', 'Dreams about girlfriends, romantic partners, or dating relationships'),
  ('husband', 'Husband', 'Dreams about husbands, spouses, or marital relationships'),
  ('wife', 'Wife', 'Dreams about wives, married women, or spousal relationships'),
  ('kiss', 'Kiss', 'Dreams about kissing someone, being kissed, or romantic moments'),
  ('marriage', 'Marriage', 'Dreams about wedding ceremonies, marriage proposals, or married life'),
  ('hate', 'Hate', 'Dreams involving hatred, intense dislike, or hostile feelings'),
  
  -- Achievement/Failure
  ('success', 'Success', 'Dreams about achieving goals or succeeding'),
  ('failure', 'Failure', 'Dreams about failing, making mistakes, or inadequacy'),
  ('exam', 'Exams/Tests', 'Dreams about taking tests, being unprepared, or being evaluated'),
  ('competition', 'Competition', 'Dreams about races, contests, or competing with others'),
  ('performance', 'Performance', 'Dreams about performing on stage or in public'),
  ('interview', 'Interview', 'Dreams about job interviews or being questioned'),
  ('race', 'Race', 'Dreams about racing, running races, or competing for speed'),
  ('test', 'Test', 'Dreams about taking tests, examinations, or being evaluated'),
  ('victory', 'Victory', 'Dreams about winning, triumph, or celebrating success'),
  ('prize', 'Prize', 'Dreams about winning prizes, trophies, or competitions'),
  ('trophy', 'Trophy', 'Dreams about trophies, awards, or winning prizes'),
  ('reward', 'Reward', 'Dreams about receiving rewards, prizes, or recognition'),
  
  -- Body/Physical
  ('naked', 'Being Naked', 'Dreams about being naked or inappropriately dressed in public'),
  ('teeth', 'Teeth Falling Out', 'Dreams about losing teeth or dental problems'),
  ('pregnancy', 'Pregnancy', 'Dreams about being pregnant or giving birth'),
  ('illness', 'Illness', 'Dreams about being sick or diseased'),
  ('injury', 'Injury', 'Dreams about being wounded, hurt, or physically damaged'),
  ('hair', 'Hair', 'Dreams about hair loss, hair changes, or hair growth'),
  ('body_parts', 'Body Parts', 'Dreams focusing on specific body parts or organs'),
  ('paralysis', 'Paralysis', 'Dreams about being unable to move or speak'),
  ('aging', 'Aging', 'Dreams about growing old or seeing oneself at different ages'),
  ('accident', 'Accident', 'Dreams about accidents, mishaps, or unexpected harmful events'),
  ('arm', 'Arm', 'Dreams about arms, reaching out, embracing, or personal strength'),
  ('blood', 'Blood', 'Dreams about blood, life force, family ties, or emotional wounds'),
  ('body', 'Body', 'Dreams about the body, physical self, health, or body image concerns'),
  ('bone', 'Bone', 'Dreams about bones, core structure, mortality, or fundamental truths'),
  ('brain', 'Brain', 'Dreams about the brain, intellect, overthinking, or mental processes'),
  ('breast', 'Breast', 'Dreams about breasts, nurturing, maternal instincts, or intimacy'),
  ('breath', 'Breath', 'Dreams about breathing, life force, anxiety, or need for space'),
  ('chest', 'Chest', 'Dreams about chests, hidden treasures, the heart, or emotional storage'),
  ('disease', 'Disease', 'Dreams about disease, fear of weakness, contamination, or inner discord'),
  ('ear', 'Ear', 'Dreams about ears, listening, rumors, or need to pay attention'),
  ('eye', 'Eye', 'Dreams focusing on eyes, eyeballs, vision problems, or being stared at'),
  ('face', 'Face', 'Dreams about faces changing, distorted faces, or inability to see faces clearly'),
  ('finger', 'Finger', 'Dreams focusing on fingers, finger injuries, or pointing gestures'),
  ('foot', 'Foot', 'Dreams focusing on feet, footsteps, shoes, or walking'),
  ('hand', 'Hand', 'Dreams focusing on hands, handshakes, or manual activities'),
  ('head', 'Head', 'Dreams focusing on heads, headaches, or head injuries'),
  ('heart', 'Heart', 'Dreams about hearts beating, heart symbols, or cardiac issues'),
  ('mouth', 'Mouth', 'Dreams focusing on mouths, speaking, eating, or dental issues'),
  ('neck', 'Neck', 'Dreams focusing on necks, neck pain, or things around the neck'),
  ('nose', 'Nose', 'Dreams focusing on noses, smelling things, or nose injuries'),
  ('pain', 'Pain', 'Dreams involving physical pain, injuries, or suffering'),
  ('scar', 'Scar', 'Dreams about scars, wounds healing, or marked skin'),
  ('shoulder', 'Shoulder', 'Dreams focusing on shoulders, shoulder pain, or carrying burdens'),
  ('skeleton', 'Skeleton', 'Dreams featuring skeletons, bones, or skeletal remains'),
  ('skin', 'Skin', 'Dreams about skin conditions, peeling skin, or skin changes'),
  ('spine', 'Spine', 'Dreams about spines, back problems, or vertebrae'),
  ('tongue', 'Tongue', 'Dreams about tongues, taste, or speech organs'),
  ('tooth', 'Tooth', 'Dreams about teeth, dental problems, or losing teeth'),
  ('vein', 'Vein', 'Dreams about veins, blood vessels, or visible veins'),
  ('wound', 'Wound', 'Dreams about wounds, injuries, or bleeding cuts'),
  ('wrist', 'Wrist', 'Dreams focusing on wrists, wrist injuries, or bracelets'),
  
  -- Nature/Animals
  ('water', 'Water', 'Dreams featuring water, oceans, rivers, or drowning'),
  ('animals', 'Animals', 'Dreams featuring animals or creatures'),
  ('natural_disaster', 'Natural Disasters', 'Dreams about earthquakes, tsunamis, storms'),
  ('snake', 'Snakes', 'Dreams featuring snakes or serpents'),
  ('spider', 'Spiders', 'Dreams about spiders or being caught in webs'),
  ('dog', 'Dogs', 'Dreams featuring dogs, puppies, or canines'),
  ('cat', 'Cats', 'Dreams featuring cats, kittens, or felines'),
  ('bird', 'Birds', 'Dreams about birds, flying creatures, or wings'),
  ('insect', 'Insects', 'Dreams about bugs, insects, or small creatures'),
  ('ocean', 'Ocean', 'Dreams about the sea, waves, or vast waters'),
  ('forest', 'Forest', 'Dreams about woods, trees, or getting lost in nature'),
  ('mountain', 'Mountains', 'Dreams about climbing, mountains, or high places'),
  ('fire', 'Fire', 'Dreams about fire, flames, or burning'),
  ('storm', 'Storms', 'Dreams about thunderstorms, lightning, or severe weather'),
  ('ant', 'Ant', 'Dreams about ants, colonies, or feelings of insignificance or industriousness'),
  ('bat', 'Bat', 'Dreams about bats, nocturnal creatures, or navigating through darkness'),
  ('bear', 'Bear', 'Dreams about bears, primal strength, protection, or hibernation'),
  ('beast', 'Beast', 'Dreams about beasts, wild nature, or untamed aspects of self'),
  ('bee', 'Bee', 'Dreams about bees, productivity, community, or feeling stung by others'),
  ('bull', 'Bull', 'Dreams about bulls, stubbornness, raw power, or aggressive energy'),
  ('butterfly', 'Butterfly', 'Dreams about butterflies, transformation, fleeting beauty, or metamorphosis'),
  ('canyon', 'Canyon', 'Dreams about canyons, deep divides, overwhelming depths, or natural forces'),
  ('coral', 'Coral', 'Dreams about coral, hidden beauty, fragile ecosystems, or collective growth'),
  ('cow', 'Cow', 'Dreams about cows, docility, nourishment, or passive acceptance'),
  ('desert', 'Desert', 'Dreams about deserts, isolation, spiritual journey, or emotional barrenness'),
  ('dinosaur', 'Dinosaur', 'Dreams about dinosaurs, outdated attitudes, primal fears, or past issues'),
  ('dolphin', 'Dolphin', 'Dreams about dolphins, playfulness, intelligence, or spiritual guides'),
  ('dragon', 'Dragon', 'Dreams about dragons, powerful forces, fears, or untamed passion'),
  ('drought', 'Drought', 'Dreams about drought, emotional dryness, lack of growth, or hard times'),
  ('duck', 'Duck', 'Dreams about ducks, emotional flexibility, or surface appearances'),
  ('eagle', 'Eagle', 'Dreams about eagles, freedom, vision, power, or rising above'),
  ('earthquake', 'Earthquake', 'Dreams about earthquakes, upheaval, unstable foundations, or major changes'),
  ('elephant', 'Elephant', 'Dreams about elephants, memory, strength, wisdom, or heavy burdens'),
  ('famine', 'Famine', 'Dreams about food shortages, starvation, or empty pantries'),
  ('feather', 'Feather', 'Dreams involving bird feathers, floating feathers, or feathered objects'),
  ('field', 'Field', 'Dreams set in open fields, meadows, or expansive grasslands'),
  ('fish', 'Fish', 'Dreams about catching fish, swimming fish, or aquatic creatures'),
  ('flood', 'Flood', 'Dreams about rising water, flooded buildings, or overwhelming waves'),
  ('flower', 'Flower', 'Dreams featuring blooming flowers, bouquets, or gardens'),
  ('fog', 'Fog', 'Dreams with thick mist, poor visibility, or clouded environments'),
  ('fox', 'Fox', 'Dreams about foxes, fox hunts, or encounters with these animals'),
  ('frog', 'Frog', 'Dreams about frogs, toads, or amphibians in ponds or gardens'),
  ('garden', 'Garden', 'Dreams set in gardens, among plants, or doing gardening work'),
  ('harvest', 'Harvest', 'Dreams about harvesting crops, gathering fruits, or reaping rewards'),
  ('horse', 'Horse', 'Dreams about riding horses, wild horses, or equestrian activities'),
  ('hurricane', 'Hurricane', 'Dreams featuring powerful storms, destructive winds, or cyclones'),
  ('ice', 'Ice', 'Dreams featuring frozen water, icy surfaces, or freezing conditions'),
  ('jungle', 'Jungle', 'Dreams set in dense jungles, tropical forests, or wild vegetation'),
  ('lake', 'Lake', 'Dreams set by lakes, swimming in calm waters, or lakeside scenes'),
  ('lava', 'Lava', 'Dreams featuring molten lava, volcanic eruptions, or flowing magma'),
  ('leaf', 'Leaf', 'Dreams about falling leaves, green foliage, or autumn scenes'),
  ('lightning', 'Lightning', 'Dreams about lightning strikes, electrical storms, or thunder'),
  ('lion', 'Lion', 'Dreams featuring lions roaring, being chased by lions, or lion prides'),
  ('meadow', 'Meadow', 'Dreams set in meadows, wildflower fields, or pastoral landscapes'),
  ('moon', 'Moon', 'Dreams about full moons, moonlight, or lunar landscapes'),
  ('mouse', 'Mouse', 'Dreams about mice, rodents scurrying, or mouse infestations'),
  ('mud', 'Mud', 'Dreams about walking through mud, getting stuck in mud, or muddy water'),
  ('nature', 'Nature', 'Dreams set in natural environments, wildlife, or outdoor scenes'),
  ('night', 'Night', 'Dreams set during nighttime, darkness, or nocturnal activities'),
  ('oak', 'Oak', 'Dreams featuring oak trees, acorns, or sturdy wood'),
  ('oasis', 'Oasis', 'Dreams about desert oases, palm trees, or water in dry places'),
  ('orchard', 'Orchard', 'Dreams set in fruit orchards, picking fruit, or rows of trees'),
  ('owl', 'Owl', 'Dreams featuring owls hooting, night birds, or wise creatures'),
  ('ox', 'Ox', 'Dreams about oxen, cattle, or beasts of burden'),
  ('palm', 'Palm', 'Dreams about palm trees, palm reading, or hand palms'),
  ('pig', 'Pig', 'Dreams featuring pigs, piglets, or farm swine'),
  ('pine', 'Pine', 'Dreams featuring pine trees, pine forests, or pine cones'),
  ('plain', 'Plain', 'Dreams set on flat plains, prairies, or wide open spaces'),
  ('plant', 'Plant', 'Dreams about plants growing, gardening, or houseplants'),
  ('pond', 'Pond', 'Dreams set by ponds, still water, or pond life'),
  ('rabbit', 'Rabbit', 'Dreams featuring rabbits, bunnies hopping, or rabbit holes'),
  ('rain', 'Rain', 'Dreams featuring rainfall, getting wet, or storms'),
  ('rainbow', 'Rainbow', 'Dreams about rainbows, colorful arcs, or pots of gold'),
  ('rat', 'Rat', 'Dreams featuring rats, rodents, or infestations'),
  ('raven', 'Raven', 'Dreams about ravens, black birds, or ominous crows'),
  ('reptile', 'Reptile', 'Dreams featuring reptiles, lizards, or cold-blooded creatures'),
  ('river', 'River', 'Dreams featuring rivers, flowing water, or crossing streams'),
  ('rock', 'Rock', 'Dreams featuring rocks, stones, or rocky terrain'),
  ('rose', 'Rose', 'Dreams about roses, thorns, or rose gardens'),
  ('sand', 'Sand', 'Dreams featuring sand, beaches, deserts, or hourglasses'),
  ('scorpion', 'Scorpion', 'Dreams about scorpions, stinging creatures, or desert arachnids'),
  ('sea', 'Sea', 'Dreams featuring seas, ocean voyages, or marine life'),
  ('seal', 'Seal', 'Dreams about seals (animals), wax seals, or sealed containers'),
  ('season', 'Season', 'Dreams featuring seasonal changes, weather patterns, or time of year'),
  ('serpent', 'Serpent', 'Dreams about serpents, large snakes, or mythical reptiles'),
  ('shark', 'Shark', 'Dreams about sharks, shark attacks, or swimming with predators'),
  ('sheep', 'Sheep', 'Dreams featuring sheep, flocks, or counting sheep'),
  ('shore', 'Shore', 'Dreams set on shores, beaches, or where land meets water'),
  ('sky', 'Sky', 'Dreams featuring skies, clouds, or looking upward'),
  ('snow', 'Snow', 'Dreams featuring snowfall, snow-covered landscapes, or blizzards'),
  ('spring', 'Spring', 'Dreams about springtime, springs of water, or coiled springs'),
  ('star', 'Star', 'Dreams featuring stars, celestial bodies, or famous people'),
  ('stream', 'Stream', 'Dreams about streams, flowing water, or brooks'),
  ('summer', 'Summer', 'Dreams set in summertime, hot weather, or vacation scenes'),
  ('sun', 'Sun', 'Dreams featuring the sun, sunlight, or solar imagery'),
  ('sunrise', 'Sunrise', 'Dreams about dawn breaking, morning sun, or new day beginning'),
  ('sunset', 'Sunset', 'Dreams featuring sunsets, dusk, or day ending'),
  ('swamp', 'Swamp', 'Dreams set in swamps, marshes, or boggy terrain'),
  ('swan', 'Swan', 'Dreams featuring swans, graceful birds, or swan lakes'),
  ('thunder', 'Thunder', 'Dreams featuring thunder, loud booms, or thunderstorms'),
  ('tide', 'Tide', 'Dreams featuring tides, ocean waves coming in, or water levels'),
  ('tiger', 'Tiger', 'Dreams about tigers, big cats, or being stalked by predators'),
  ('tornado', 'Tornado', 'Dreams about tornadoes, twisters, or swirling winds'),
  ('tree', 'Tree', 'Dreams featuring trees, forests, or climbing trees'),
  ('turkey', 'Turkey', 'Dreams featuring turkeys, birds, or holiday meals'),
  ('turtle', 'Turtle', 'Dreams featuring turtles, tortoises, or slow-moving creatures'),
  ('valley', 'Valley', 'Dreams set in valleys, between mountains, or low-lying areas'),
  ('vine', 'Vine', 'Dreams featuring vines, climbing plants, or tangled growth'),
  ('volcano', 'Volcano', 'Dreams featuring volcanoes, eruptions, or lava flows'),
  ('vulture', 'Vulture', 'Dreams featuring vultures, scavenger birds, or circling predators'),
  ('waterfall', 'Waterfall', 'Dreams about waterfalls, cascading water, or falling torrents'),
  ('wave', 'Wave', 'Dreams featuring ocean waves, tidal waves, or waving gestures'),
  ('weather', 'Weather', 'Dreams about weather conditions, storms, or climate changes'),
  ('whale', 'Whale', 'Dreams about whales, sea giants, or whale watching'),
  ('wheat', 'Wheat', 'Dreams featuring wheat fields, grain, or harvests'),
  ('wind', 'Wind', 'Dreams featuring wind, breezes, or strong gusts'),
  ('winter', 'Winter', 'Dreams set in winter, snow scenes, or cold weather'),
  ('wolf', 'Wolf', 'Dreams about wolves, wolf packs, or being chased by wolves'),
  ('worm', 'Worm', 'Dreams featuring worms, earthworms, or crawling creatures'),
  ('zebra', 'Zebra', 'Dreams featuring zebras, striped animals, or safari scenes'),
  ('zoo', 'Zoo', 'Dreams set in zoos, caged animals, or wildlife parks'),
  
  -- Supernatural/Spiritual
  ('supernatural', 'Supernatural', 'Dreams about ghosts, spirits, or paranormal events'),
  ('religious', 'Religious/Spiritual', 'Dreams with religious or spiritual themes'),
  ('transformation', 'Transformation', 'Dreams about changing form or metamorphosis'),
  ('demon', 'Demons', 'Dreams about demons, devils, or evil entities'),
  ('angel', 'Angels', 'Dreams about angels, divine beings, or protectors'),
  ('magic', 'Magic', 'Dreams about magical powers, spells, or supernatural abilities'),
  ('afterlife', 'Afterlife', 'Dreams about heaven, hell, or life after death'),
  ('god', 'Divine Beings', 'Dreams about gods, goddesses, or supreme beings'),
  ('ritual', 'Rituals', 'Dreams about ceremonies, rituals, or sacred practices'),
  ('vampire', 'Vampires', 'Dreams about vampires, blood-drinking, or immortal beings'),
  ('witch', 'Witches', 'Dreams about witches, witchcraft, or sorcery'),
  ('altar', 'Altar', 'Dreams about altars, sacred spaces, or places of worship and sacrifice'),
  ('ghost', 'Ghost', 'Dreams featuring spirits, apparitions, or haunted places'),
  ('heaven', 'Heaven', 'Dreams about celestial realms, clouds, or paradise settings'),
  ('hell', 'Hell', 'Dreams about infernal places, fire and brimstone, or underworlds'),
  ('magician', 'Magician', 'Dreams featuring magicians, illusionists, or stage performances'),
  ('miracle', 'Miracle', 'Dreams about miraculous events, impossible occurrences, or divine intervention'),
  ('oracle', 'Oracle', 'Dreams featuring fortune tellers, prophecies, or mystical advisors'),
  ('paradise', 'Paradise', 'Dreams set in paradisiacal locations, perfect places, or utopias'),
  ('prophet', 'Prophet', 'Dreams featuring prophets, predictions, or religious visions'),
  ('soul', 'Soul', 'Dreams about souls, spirit forms, or out-of-body experiences'),
  ('spell', 'Spell', 'Dreams featuring magic spells, casting spells, or being enchanted'),
  ('spirit', 'Spirit', 'Dreams about spirits, ghostly beings, or spiritual presences'),
  ('wizard', 'Wizard', 'Dreams featuring wizards, magical men, or sorcerers'),
  
  -- Travel/Journey
  ('travel', 'Travel', 'Dreams about journeys, trips, or transportation'),
  ('vehicle', 'Vehicles', 'Dreams about cars, planes, or other vehicles'),
  ('late', 'Being Late', 'Dreams about running late or missing appointments'),
  ('train', 'Trains', 'Dreams about trains, railways, or train stations'),
  ('airplane', 'Airplanes', 'Dreams about flying in planes or airports'),
  ('ship', 'Ships', 'Dreams about boats, ships, or sailing'),
  ('car_accident', 'Car Accidents', 'Dreams about vehicle crashes or collisions'),
  ('road', 'Roads', 'Dreams about paths, highways, or journeys'),
  ('bridge', 'Bridges', 'Dreams about crossing bridges or transitions'),
  ('bicycle', 'Bicycle', 'Dreams about bicycles, balance, self-reliance, or moving forward in life'),
  ('boat', 'Boat', 'Dreams about boats, navigating emotions, or journeys across the unconscious'),
  ('bus', 'Bus', 'Dreams about buses, collective journey, conformity, or shared direction'),
  ('car', 'Car', 'Dreams about cars, personal drive, life direction, or control over destiny'),
  ('flight', 'Flight', 'Dreams about airplane flights, flying creatures, or aerial travel'),
  ('journey', 'Journey', 'Dreams about traveling, long trips, or expeditions to distant places'),
  ('passage', 'Passage', 'Dreams about passages, tunnels, or narrow walkways'),
  ('passenger', 'Passenger', 'Dreams about being a passenger in vehicles, trains, or planes'),
  ('path', 'Path', 'Dreams about walking paths, choosing directions, or forest trails'),
  ('pilot', 'Pilot', 'Dreams about pilots flying planes, cockpits, or aviation uniforms'),
  ('plane', 'Plane', 'Dreams about airplanes, flying in planes, or plane crashes'),
  ('platform', 'Platform', 'Dreams about train platforms, stages, or raised surfaces'),
  ('raft', 'Raft', 'Dreams about rafts, floating on water, or makeshift boats'),
  ('rocket', 'Rocket', 'Dreams about rockets, space launches, or missiles'),
  ('sail', 'Sail', 'Dreams about sailing, boat sails, or wind in sails'),
  ('sailor', 'Sailor', 'Dreams featuring sailors, naval uniforms, or seafaring'),
  ('station', 'Station', 'Dreams set in stations, train stations, or waiting areas'),
  ('subway', 'Subway', 'Dreams set in subways, underground trains, or metro systems'),
  ('track', 'Track', 'Dreams about tracks, railways, or following trails'),
  ('truck', 'Truck', 'Dreams featuring trucks, large vehicles, or cargo transport'),
  ('voyage', 'Voyage', 'Dreams about sea voyages, long journeys, or expeditions'),
  
  -- Conflict/Violence
  ('conflict', 'Conflict', 'Dreams about arguments, fights, or confrontations'),
  ('war', 'War', 'Dreams about war, battle, or large-scale conflict'),
  ('violence', 'Violence', 'Dreams involving violent acts or aggression'),
  ('murder', 'Murder', 'Dreams about killing or being killed'),
  ('weapon', 'Weapons', 'Dreams featuring guns, knives, or other weapons'),
  ('invasion', 'Invasion', 'Dreams about being invaded or territory being violated'),
  ('prison', 'Prison', 'Dreams about jail, confinement, or captivity'),
  ('crime', 'Crime', 'Dreams about criminal acts or being a victim of crime'),
  ('battle', 'Battle', 'Dreams about battles, internal conflicts, or fighting for beliefs'),
  ('bomb', 'Bomb', 'Dreams about bombs, explosive emotions, or destructive potential'),
  ('bullet', 'Bullet', 'Dreams about bullets, direct confrontation, words that wound, or danger'),
  ('enemy', 'Enemy', 'Dreams featuring adversaries, opponents, or people who wish you harm'),
  ('explosion', 'Explosion', 'Dreams featuring bombs exploding, buildings blowing up, or sudden blasts'),
  ('fight', 'Fight', 'Dreams involving physical combat, arguments, or violent confrontations'),
  ('gun', 'Gun', 'Dreams involving firearms, shooting, or being threatened with weapons'),
  ('jail', 'Jail', 'Dreams about prison cells, being imprisoned, or visiting inmates'),
  ('knife', 'Knife', 'Dreams featuring knives, cutting, stabbing, or sharp blades'),
  ('robber', 'Robber', 'Dreams about robbers, theft, or being robbed'),
  ('soldier', 'Soldier', 'Dreams about soldiers, military personnel, or armies'),
  ('spear', 'Spear', 'Dreams about spears, being speared, or throwing weapons'),
  ('sword', 'Sword', 'Dreams about swords, sword fighting, or bladed weapons'),
  ('thief', 'Thief', 'Dreams featuring thieves, burglars, or stolen items'),
  ('warrior', 'Warrior', 'Dreams about warriors, fighters, or battle-ready figures'),
  
  -- Home/Places
  ('home', 'Home', 'Dreams about your home or childhood home'),
  ('work', 'Work/School', 'Dreams about workplace or school environments'),
  ('unfamiliar_place', 'Unfamiliar Places', 'Dreams about strange or unknown locations'),
  ('basement', 'Basement', 'Dreams about basements, cellars, or underground spaces'),
  ('attic', 'Attic', 'Dreams about attics, upper rooms, or hidden spaces'),
  ('bathroom', 'Bathroom', 'Dreams about bathrooms, toilets, or privacy'),
  ('hospital', 'Hospital', 'Dreams about hospitals, medical facilities, or healing'),
  ('cemetery', 'Cemetery', 'Dreams about graveyards, tombstones, or burial grounds'),
  ('church', 'Church/Temple', 'Dreams about religious buildings or sacred spaces'),
  ('hotel', 'Hotel', 'Dreams about hotels, temporary lodging, or transient spaces'),
  ('mall', 'Shopping Mall', 'Dreams about shopping centers or marketplaces'),
  ('castle', 'Castle', 'Dreams about castles, fortresses, or grand buildings'),
  ('maze', 'Maze/Labyrinth', 'Dreams about being lost in mazes or complex paths'),
  ('apartment', 'Apartment', 'Dreams about apartments, temporary homes, or transitional living spaces'),
  ('bank', 'Bank', 'Dreams about banks, financial security, or stored resources and potential'),
  ('barn', 'Barn', 'Dreams about barns, rural life, storage, or hidden aspects of personality'),
  ('beach', 'Beach', 'Dreams about beaches, boundaries between conscious and unconscious mind'),
  ('bed', 'Bed', 'Dreams about beds, rest, intimacy, or private thoughts and desires'),
  ('building', 'Building', 'Dreams about buildings, the self, ambitions, or constructed identities'),
  ('cage', 'Cage', 'Dreams about cages, feeling trapped, self-imposed limitations, or protection'),
  ('cave', 'Cave', 'Dreams about caves, the womb, hidden knowledge, or primitive shelter'),
  ('ceiling', 'Ceiling', 'Dreams about ceilings, limitations, aspirations, or protective barriers'),
  ('city', 'City', 'Dreams about cities, social life, opportunities, or feeling overwhelmed'),
  ('cliff', 'Cliff', 'Dreams about cliffs, dangerous decisions, or being on the edge'),
  ('closet', 'Closet', 'Dreams about closets, hidden aspects, secrets, or coming out'),
  ('corridor', 'Corridor', 'Dreams about corridors, transitions, choices, or paths between phases'),
  ('country', 'Country', 'Dreams about countries, belonging, cultural identity, or foreign experiences'),
  ('court', 'Court', 'Dreams about courts, judgment, guilt, justice, or being on trial'),
  ('door', 'Door', 'Dreams about doors, opportunities, transitions, or closed possibilities'),
  ('elevator', 'Elevator', 'Dreams where you ride elevators up or down, get stuck between floors, or experience elevator malfunctions'),
  ('entrance', 'Entrance', 'Dreams about doorways, entryways, gates, or portals to buildings or spaces'),
  ('factory', 'Factory', 'Dreams set in industrial buildings, assembly lines, or manufacturing plants'),
  ('farm', 'Farm', 'Dreams set on farms with crops, barns, livestock, or agricultural work'),
  ('fence', 'Fence', 'Dreams about fences, walls, barriers, or property boundaries'),
  ('floor', 'Floor', 'Dreams focusing on floors, flooring, or ground surfaces inside buildings'),
  ('fountain', 'Fountain', 'Dreams featuring water fountains, springs, or decorative water features'),
  ('gate', 'Gate', 'Dreams about gates opening or closing, locked gates, or gateways'),
  ('grave', 'Grave', 'Dreams about graveyards, tombstones, or burial sites'),
  ('ground', 'Ground', 'Dreams focusing on the earth, soil, or terrain beneath you'),
  ('hall', 'Hall', 'Dreams set in hallways, corridors, or long passages'),
  ('harbor', 'Harbor', 'Dreams set in ports, marinas, or coastal docking areas'),
  ('hill', 'Hill', 'Dreams about climbing hills, rolling hills, or hilltop views'),
  ('hole', 'Hole', 'Dreams about falling into holes, digging holes, or gaps in the ground'),
  ('house', 'House', 'Dreams featuring houses, exploring rooms, or residential buildings'),
  ('island', 'Island', 'Dreams set on islands, surrounded by water, or tropical paradises'),
  ('kitchen', 'Kitchen', 'Dreams set in kitchens, cooking meals, or kitchen appliances'),
  ('labyrinth', 'Labyrinth', 'Dreams about complex mazes, winding paths, or getting lost in passages'),
  ('library', 'Library', 'Dreams set in libraries, searching for books, or quiet reading rooms'),
  ('market', 'Market', 'Dreams set in marketplaces, shopping for goods, or crowded bazaars'),
  ('mine', 'Mine', 'Dreams set in underground mines, digging for minerals, or cave-ins'),
  ('office', 'Office', 'Dreams set in office buildings, workplaces, or cubicles'),
  ('palace', 'Palace', 'Dreams set in palaces, grand halls, or royal residences'),
  ('park', 'Park', 'Dreams set in parks, playgrounds, or public green spaces'),
  ('pit', 'Pit', 'Dreams about falling into pits, deep holes, or bottomless chasms'),
  ('place', 'Place', 'Dreams about specific places, locations, or unfamiliar settings'),
  ('playground', 'Playground', 'Dreams set in playgrounds, swings, slides, or childhood play areas'),
  ('pool', 'Pool', 'Dreams about swimming pools, diving, or poolside scenes'),
  ('portal', 'Portal', 'Dreams featuring magical portals, doorways to other dimensions, or passages'),
  ('pyramid', 'Pyramid', 'Dreams featuring pyramids, ancient Egypt, or triangular structures'),
  ('realm', 'Realm', 'Dreams about fantasy realms, kingdoms, or other dimensions'),
  ('restaurant', 'Restaurant', 'Dreams set in restaurants, ordering food, or dining out'),
  ('roof', 'Roof', 'Dreams about rooftops, climbing on roofs, or roof damage'),
  ('room', 'Room', 'Dreams set in rooms, exploring rooms, or locked rooms'),
  ('ruins', 'Ruins', 'Dreams set in ruins, ancient structures, or crumbling buildings'),
  ('school', 'School', 'Dreams set in schools, classrooms, or taking exams'),
  ('shelter', 'Shelter', 'Dreams about finding shelter, protective structures, or hiding places'),
  ('shop', 'Shop', 'Dreams about shopping, stores, or browsing merchandise'),
  ('shrine', 'Shrine', 'Dreams featuring shrines, sacred places, or memorial sites'),
  ('stage', 'Stage', 'Dreams set on stages, theatrical performances, or being on display'),
  ('stair', 'Stair', 'Dreams about stairs, climbing steps, or descending staircases'),
  ('street', 'Street', 'Dreams set on streets, city roads, or neighborhoods'),
  ('temple', 'Temple', 'Dreams set in temples, sacred buildings, or places of worship'),
  ('tent', 'Tent', 'Dreams featuring tents, camping, or temporary shelters'),
  ('throne', 'Throne', 'Dreams featuring thrones, royal seats, or positions of power'),
  ('tomb', 'Tomb', 'Dreams featuring tombs, crypts, or burial chambers'),
  ('tower', 'Tower', 'Dreams featuring towers, tall structures, or climbing high'),
  ('town', 'Town', 'Dreams set in towns, small communities, or familiar places'),
  ('tunnel', 'Tunnel', 'Dreams about tunnels, underground passages, or dark corridors'),
  ('vault', 'Vault', 'Dreams featuring bank vaults, secure rooms, or underground chambers'),
  ('village', 'Village', 'Dreams set in villages, small towns, or rural communities'),
  ('wall', 'Wall', 'Dreams featuring walls, barriers, or climbing walls'),
  ('well', 'Well', 'Dreams featuring wells, deep holes with water, or wishing wells'),
  ('window', 'Window', 'Dreams about windows, looking through glass, or broken windows'),
  ('yard', 'Yard', 'Dreams set in yards, backyards, or outdoor home spaces'),
  
  -- Technology/Modern
  ('technology', 'Technology', 'Dreams about computers, phones, or technology'),
  ('social_media', 'Social Media', 'Dreams about social media or online interactions'),
  ('phone', 'Phone', 'Dreams about phone calls, messages, or communication devices'),
  ('computer', 'Computer', 'Dreams about computers, screens, or digital interfaces'),
  ('robot', 'Robots', 'Dreams about robots, androids, or mechanical beings'),
  ('ai', 'Artificial Intelligence', 'Dreams about AI, AGI, LLMs, chatbots,ChatGPT, or other AI-powered systems'),
  ('vr', 'Virtual Reality', 'Dreams about VR, Oculus, Meta, or other VR-related experiences'),
  ('space', 'Space', 'Dreams about space, rockets, moon, aliens, or outer space'),
  ('cyberpunk', 'Cyberpunk', 'Dreams about cyberpunk, bioimplants, or futuristic cities'),
  ('camera', 'Camera', 'Dreams about cameras, capturing memories, observation, or self-image'),
  ('engine', 'Engine', 'Dreams involving car engines, machinery, or mechanical components'),
  ('machine', 'Machine', 'Dreams featuring complex machinery, operating equipment, or mechanical devices'),
  ('photograph', 'Photograph', 'Dreams about taking photos, old photographs, or photo albums'),
  ('radio', 'Radio', 'Dreams featuring radios, radio broadcasts, or static noise'),
  ('satellite', 'Satellite', 'Dreams about satellites, space objects, or communication devices'),
  ('screen', 'Screen', 'Dreams featuring screens, monitors, or movie screens'),
  ('telephone', 'Telephone', 'Dreams featuring telephones, phone calls, or ringing phones'),
  ('telescope', 'Telescope', 'Dreams about telescopes, looking through lenses, or distant viewing'),
  ('web', 'Web', 'Dreams featuring spider webs, tangled webs, or internet'),
  
  -- Emotions
  ('anxiety', 'Anxiety', 'Dreams characterized by anxiety or worry'),
  ('joy', 'Joy/Happiness', 'Dreams characterized by joy or happiness'),
  ('fear', 'Fear', 'Dreams characterized by fear or terror'),
  ('sadness', 'Sadness', 'Dreams characterized by sadness or grief'),
  ('anger', 'Anger', 'Dreams characterized by rage, fury, or frustration'),
  ('guilt', 'Guilt', 'Dreams characterized by guilt, shame, or regret'),
  ('loneliness', 'Loneliness', 'Dreams characterized by isolation or being alone'),
  ('peace', 'Peace', 'Dreams about peaceful scenes, tranquility, or conflict resolution'),
  ('rage', 'Rage', 'Dreams involving intense anger, fury, or violent outbursts'),
  ('terror', 'Terror', 'Dreams involving extreme fear, terrifying events, or panic'),
  
  -- Objects/Items
  ('money', 'Money', 'Dreams about wealth, coins, bills, or financial matters'),
  ('key', 'Keys', 'Dreams about keys, locks, or access'),
  ('mirror', 'Mirrors', 'Dreams about reflections, mirrors, or self-image'),
  ('box', 'Boxes', 'Dreams about containers, packages, or hidden contents'),
  ('book', 'Books', 'Dreams about reading, books, or knowledge'),
  ('jewelry', 'Jewelry', 'Dreams about gems, rings, or precious items'),
  ('food', 'Food', 'Dreams about eating, cooking, or food'),
  ('clothes', 'Clothing', 'Dreams about clothes, dressing, or appearance'),
  ('treasure', 'Treasure', 'Dreams about finding treasure or valuable items'),
  ('letter', 'Letters/Messages', 'Dreams about receiving mail or important messages'),
  ('gift', 'Gifts', 'Dreams about giving or receiving presents'),
  ('anchor', 'Anchor', 'Dreams about anchors, stability, or being grounded or held in place'),
  ('apple', 'Apple', 'Dreams about apples, forbidden fruit, or temptation and knowledge'),
  ('arrow', 'Arrow', 'Dreams about arrows, direction, focus, or being targeted'),
  ('ash', 'Ash', 'Dreams about ashes, remnants of destruction, or transformation through fire'),
  ('bag', 'Bag', 'Dreams about bags, baggage, burdens, or things you carry with you'),
  ('ball', 'Ball', 'Dreams about balls, spheres, games, or social gatherings'),
  ('balloon', 'Balloon', 'Dreams about balloons, celebration, lightness, or things that could burst'),
  ('barrier', 'Barrier', 'Dreams about barriers, obstacles, limitations, or blocked progress'),
  ('bath', 'Bath', 'Dreams about bathing, cleansing, renewal, or emotional purification'),
  ('bell', 'Bell', 'Dreams about bells, announcements, warnings, or calls to attention'),
  ('belt', 'Belt', 'Dreams about belts, restraint, control, or holding things together'),
  ('bench', 'Bench', 'Dreams about benches, taking a break, or observing life from the sidelines'),
  ('blanket', 'Blanket', 'Dreams about blankets, comfort, security, or hiding from reality'),
  ('bottle', 'Bottle', 'Dreams about bottles, contained emotions, or messages waiting to be released'),
  ('branch', 'Branch', 'Dreams about branches, life choices, family connections, or growth'),
  ('bread', 'Bread', 'Dreams about bread, sustenance, basic needs, or spiritual nourishment'),
  ('brick', 'Brick', 'Dreams about bricks, building blocks, solid foundations, or barriers'),
  ('bubble', 'Bubble', 'Dreams about bubbles, fragility, temporary joy, or isolated realities'),
  ('button', 'Button', 'Dreams about buttons, choices, activation, or holding things together'),
  ('cake', 'Cake', 'Dreams about cake, celebration, rewards, indulgence, or special occasions'),
  ('candle', 'Candle', 'Dreams about candles, illumination, hope, spirituality, or time passing'),
  ('card', 'Card', 'Dreams about cards, chance, hidden information, or playing your hand'),
  ('carpet', 'Carpet', 'Dreams about carpets, comfort, covering up, or foundations of home'),
  ('chain', 'Chain', 'Dreams about chains, bondage, connections, restrictions, or linked events'),
  ('chair', 'Chair', 'Dreams about chairs, position in life, need to rest, or authority'),
  ('cheese', 'Cheese', 'Dreams about cheese, abundance, patience, transformation, or simple pleasures'),
  ('circle', 'Circle', 'Dreams about circles, wholeness, cycles, or going in circles'),
  ('clock', 'Clock', 'Dreams about clocks, time pressure, deadlines, or life passing by'),
  ('cloud', 'Cloud', 'Dreams about clouds, confusion, emotions, or temporary obstacles'),
  ('coat', 'Coat', 'Dreams about coats, protection, public image, or emotional covering'),
  ('coffin', 'Coffin', 'Dreams about coffins, endings, transformation, or burying the past'),
  ('coin', 'Coin', 'Dreams about coins, small gains, decisions, or two sides of an issue'),
  ('collar', 'Collar', 'Dreams about collars, restrictions, control, or professional identity'),
  ('color', 'Color', 'Dreams featuring vivid colors, emotions, or life vibrancy'),
  ('compass', 'Compass', 'Dreams about compasses, finding direction, guidance, or moral orientation'),
  ('costume', 'Costume', 'Dreams about costumes, false identity, roles we play, or hiding true self'),
  ('crack', 'Crack', 'Dreams about cracks, flaws, breaking points, or hidden vulnerabilities'),
  ('cradle', 'Cradle', 'Dreams about cradles, nurturing, new projects, or childhood needs'),
  ('cross', 'Cross', 'Dreams about crosses, burdens, sacrifice, faith, or intersections'),
  ('crown', 'Crown', 'Dreams about crowns, authority, achievement, success, or power'),
  ('crystal', 'Crystal', 'Dreams about crystals, clarity, healing, spiritual energy, or transparency'),
  ('cup', 'Cup', 'Dreams about cups, emotional capacity, nourishment, or offerings'),
  ('curtain', 'Curtain', 'Dreams about curtains, concealment, privacy, or revealing truth'),
  ('diamond', 'Diamond', 'Dreams about diamonds, value, pressure creating beauty, or lasting love'),
  ('doll', 'Doll', 'Dreams about dolls, childhood, manipulation, or idealized self-image'),
  ('dress', 'Dress', 'Dreams about dresses, femininity, self-presentation, or social image'),
  ('drum', 'Drum', 'Dreams about drums, heartbeat, primal rhythms, or call to action'),
  ('dust', 'Dust', 'Dreams about dust, neglect, passing time, or things forgotten'),
  ('echo', 'Echo', 'Dreams about echoes, past reverberations, repetition, or hollow feelings'),
  ('egg', 'Egg', 'Dreams about eggs, potential, fragility, new beginnings, or fertility'),
  ('flag', 'Flag', 'Dreams featuring flags, banners, or national symbols waving'),
  ('flame', 'Flame', 'Dreams about candle flames, torch fire, or flickering lights'),
  ('fruit', 'Fruit', 'Dreams featuring apples, oranges, berries, or fruit trees'),
  ('glove', 'Glove', 'Dreams featuring gloves, mittens, or hand coverings'),
  ('gold', 'Gold', 'Dreams about gold coins, treasures, or golden objects'),
  ('hammer', 'Hammer', 'Dreams featuring hammers, nails, or construction work'),
  ('hat', 'Hat', 'Dreams about wearing hats, losing hats, or various headwear'),
  ('honey', 'Honey', 'Dreams featuring honey, beehives, or sticky sweet substances'),
  ('hook', 'Hook', 'Dreams about fishing hooks, being hooked, or curved metal objects'),
  ('horn', 'Horn', 'Dreams featuring animal horns, car horns, or musical horns'),
  ('hour', 'Hour', 'Dreams about checking time, specific hours, or clocks showing time'),
  ('idol', 'Idol', 'Dreams about statues, religious idols, or celebrity figures'),
  ('jewel', 'Jewel', 'Dreams featuring precious gems, jewelry boxes, or sparkling stones'),
  ('kite', 'Kite', 'Dreams about flying kites, tangled strings, or kites in the wind'),
  ('knot', 'Knot', 'Dreams about tying knots, tangled ropes, or being bound'),
  ('ladder', 'Ladder', 'Dreams about climbing ladders, broken rungs, or reaching heights'),
  ('lamp', 'Lamp', 'Dreams featuring lamps, lamplight, or searching with lanterns'),
  ('light', 'Light', 'Dreams featuring bright lights, illumination, or searching for light switches'),
  ('line', 'Line', 'Dreams about standing in lines, drawing lines, or crossing boundaries'),
  ('lock', 'Lock', 'Dreams about locked doors, padlocks, or trying to open locks'),
  ('map', 'Map', 'Dreams about reading maps, getting directions, or charting courses'),
  ('mask', 'Mask', 'Dreams about wearing masks, masked figures, or disguised identities'),
  ('meat', 'Meat', 'Dreams about eating meat, butcher shops, or raw flesh'),
  ('medicine', 'Medicine', 'Dreams about taking pills, medical treatments, or healing remedies'),
  ('message', 'Message', 'Dreams about receiving messages, texts, or important communications'),
  ('metal', 'Metal', 'Dreams featuring metal objects, steel structures, or metallic surfaces'),
  ('milk', 'Milk', 'Dreams about drinking milk, spilled milk, or dairy products'),
  ('nail', 'Nail', 'Dreams about fingernails, hammering nails, or nail injuries'),
  ('needle', 'Needle', 'Dreams about sewing needles, injections, or being pricked'),
  ('net', 'Net', 'Dreams about fishing nets, being caught in nets, or safety nets'),
  ('noise', 'Noise', 'Dreams featuring loud sounds, disturbing noises, or cacophony'),
  ('note', 'Note', 'Dreams about written notes, musical notes, or leaving messages'),
  ('number', 'Number', 'Dreams featuring specific numbers, counting, or numerical sequences'),
  ('nut', 'Nut', 'Dreams about eating nuts, cracking shells, or nut trees'),
  ('oil', 'Oil', 'Dreams about oil spills, cooking oil, or petroleum'),
  ('orange', 'Orange', 'Dreams about orange fruit, orange color, or citrus groves'),
  ('organ', 'Organ', 'Dreams about body organs, church organs, or organ music'),
  ('package', 'Package', 'Dreams about receiving packages, wrapped parcels, or deliveries'),
  ('page', 'Page', 'Dreams about book pages, blank pages, or turning pages'),
  ('paint', 'Paint', 'Dreams about painting walls, art creation, or paint spills'),
  ('paper', 'Paper', 'Dreams featuring paper documents, blank sheets, or paperwork'),
  ('pattern', 'Pattern', 'Dreams featuring repeating patterns, designs, or sequences'),
  ('pearl', 'Pearl', 'Dreams featuring pearls, pearl necklaces, or diving for pearls'),
  ('pen', 'Pen', 'Dreams about writing with pens, signing documents, or ink'),
  ('pencil', 'Pencil', 'Dreams about pencils, sketching, or erasing mistakes'),
  ('perfume', 'Perfume', 'Dreams about fragrances, scent bottles, or overwhelming smells'),
  ('piano', 'Piano', 'Dreams featuring pianos, playing piano, or piano music'),
  ('picture', 'Picture', 'Dreams about pictures on walls, drawing pictures, or imagery'),
  ('pill', 'Pill', 'Dreams about taking pills, medication, or swallowing tablets'),
  ('pillar', 'Pillar', 'Dreams featuring pillars, columns, or structural supports'),
  ('pillow', 'Pillow', 'Dreams about pillows, pillow fights, or sleeping comfort'),
  ('plate', 'Plate', 'Dreams featuring plates of food, broken dishes, or empty plates'),
  ('pocket', 'Pocket', 'Dreams about pockets, finding things in pockets, or holes in pockets'),
  ('poem', 'Poem', 'Dreams about writing poetry, reading poems, or reciting verses'),
  ('poison', 'Poison', 'Dreams about being poisoned, toxic substances, or poison bottles'),
  ('pole', 'Pole', 'Dreams featuring poles, flag poles, or pole climbing'),
  ('portrait', 'Portrait', 'Dreams about portraits, painted faces, or sitting for paintings'),
  ('pot', 'Pot', 'Dreams featuring cooking pots, plant pots, or containers'),
  ('powder', 'Powder', 'Dreams about powder substances, makeup powder, or dust'),
  ('present', 'Present', 'Dreams about wrapped presents, gift-giving, or surprises'),
  ('puddle', 'Puddle', 'Dreams about stepping in puddles, water puddles, or reflections'),
  ('puppet', 'Puppet', 'Dreams featuring puppets, marionettes, or puppet shows'),
  ('purse', 'Purse', 'Dreams about purses, handbags, losing purses, or finding money in purses'),
  ('puzzle', 'Puzzle', 'Dreams about solving puzzles, jigsaw pieces, or missing pieces'),
  ('ray', 'Ray', 'Dreams featuring rays of light, sun rays, or beams'),
  ('receipt', 'Receipt', 'Dreams about receipts, bills, or proof of purchase'),
  ('recipe', 'Recipe', 'Dreams featuring recipes, cooking instructions, or ingredients'),
  ('record', 'Record', 'Dreams about vinyl records, recording something, or breaking records'),
  ('ribbon', 'Ribbon', 'Dreams featuring ribbons, bows, or decorative strips'),
  ('rice', 'Rice', 'Dreams about rice fields, eating rice, or grains'),
  ('ring', 'Ring', 'Dreams featuring rings, wedding bands, or circular objects'),
  ('robe', 'Robe', 'Dreams featuring robes, gowns, or ceremonial clothing'),
  ('rope', 'Rope', 'Dreams featuring ropes, being tied up, or climbing ropes'),
  ('saddle', 'Saddle', 'Dreams featuring saddles, horseback riding, or mounting animals'),
  ('salt', 'Salt', 'Dreams about salt, seasoning food, or salt water'),
  ('scale', 'Scale', 'Dreams featuring scales, weighing things, or fish scales'),
  ('scissors', 'Scissors', 'Dreams featuring scissors, cutting things, or sharp blades'),
  ('scroll', 'Scroll', 'Dreams about ancient scrolls, rolled documents, or sacred texts'),
  ('seat', 'Seat', 'Dreams about seats, finding a place to sit, or assigned seating'),
  ('seed', 'Seed', 'Dreams featuring seeds, planting, or growth potential'),
  ('shape', 'Shape', 'Dreams featuring geometric shapes, shifting forms, or patterns'),
  ('sheet', 'Sheet', 'Dreams about bed sheets, paper sheets, or fabric'),
  ('shelf', 'Shelf', 'Dreams featuring shelves, storing items, or things falling off shelves'),
  ('shell', 'Shell', 'Dreams about seashells, turtle shells, or protective coverings'),
  ('shield', 'Shield', 'Dreams featuring shields, protection, or defensive equipment'),
  ('shirt', 'Shirt', 'Dreams featuring shirts, clothing, or getting dressed'),
  ('shoe', 'Shoe', 'Dreams about shoes, losing shoes, or trying on footwear'),
  ('sign', 'Sign', 'Dreams featuring signs, road signs, or symbolic messages'),
  ('silk', 'Silk', 'Dreams featuring silk fabric, silky textures, or luxurious materials'),
  ('silver', 'Silver', 'Dreams about silver objects, coins, or metallic shine'),
  ('smoke', 'Smoke', 'Dreams featuring smoke, smoking, or smoky environments'),
  ('song', 'Song', 'Dreams about hearing songs, singing, or musical melodies'),
  ('sound', 'Sound', 'Dreams featuring specific sounds, noises, or auditory experiences'),
  ('soup', 'Soup', 'Dreams about eating soup, cooking soup, or bowls of broth'),
  ('spark', 'Spark', 'Dreams featuring sparks, electrical sparks, or small fires'),
  ('sphere', 'Sphere', 'Dreams about spheres, orbs, or perfectly round objects'),
  ('spoon', 'Spoon', 'Dreams featuring spoons, eating utensils, or stirring'),
  ('square', 'Square', 'Dreams featuring squares, town squares, or square shapes'),
  ('staff', 'Staff', 'Dreams about staffs, walking sticks, or groups of employees'),
  ('statue', 'Statue', 'Dreams featuring statues, monuments, or frozen figures'),
  ('steam', 'Steam', 'Dreams about steam, vapor, or steamy environments'),
  ('steel', 'Steel', 'Dreams featuring steel objects, metal structures, or strength'),
  ('step', 'Step', 'Dreams about taking steps, footsteps, or step-by-step processes'),
  ('stick', 'Stick', 'Dreams featuring sticks, branches, or wooden rods'),
  ('stone', 'Stone', 'Dreams about stones, rocks, or being turned to stone'),
  ('string', 'String', 'Dreams featuring strings, thread, or tangled cords'),
  ('sugar', 'Sugar', 'Dreams about sugar, sweetness, or sugary foods'),
  ('suit', 'Suit', 'Dreams featuring suits, formal wear, or business attire'),
  ('symbol', 'Symbol', 'Dreams featuring symbols, signs, or meaningful imagery'),
  ('table', 'Table', 'Dreams featuring tables, dining tables, or table settings'),
  ('tail', 'Tail', 'Dreams about tails, animal tails, or things following behind'),
  ('tear', 'Tear', 'Dreams about tears, crying, or ripped fabric'),
  ('thing', 'Thing', 'Dreams about unidentified objects, strange things, or unnamed items'),
  ('thorn', 'Thorn', 'Dreams featuring thorns, prickly plants, or being pricked'),
  ('thread', 'Thread', 'Dreams about threads, sewing thread, or thin connections'),
  ('ticket', 'Ticket', 'Dreams about tickets, admission passes, or travel documents'),
  ('tool', 'Tool', 'Dreams featuring tools, equipment, or implements'),
  ('torch', 'Torch', 'Dreams featuring torches, flame lights, or carrying fire'),
  ('toy', 'Toy', 'Dreams featuring toys, playthings, or childhood objects'),
  ('trash', 'Trash', 'Dreams featuring garbage, waste, or throwing things away'),
  ('trigger', 'Trigger', 'Dreams featuring triggers, gun triggers, or activating mechanisms'),
  ('trunk', 'Trunk', 'Dreams featuring trunks, storage chests, or elephant trunks'),
  ('umbrella', 'Umbrella', 'Dreams about umbrellas, rain protection, or opening umbrellas'),
  ('uniform', 'Uniform', 'Dreams about wearing uniforms, military dress, or work clothes'),
  ('vase', 'Vase', 'Dreams about vases, flower containers, or breaking pottery'),
  ('veil', 'Veil', 'Dreams featuring veils, face coverings, or bridal veils'),
  ('vessel', 'Vessel', 'Dreams featuring vessels, ships, or containers'),
  ('violin', 'Violin', 'Dreams about violins, string music, or playing instruments'),
  ('wand', 'Wand', 'Dreams about magic wands, wizard tools, or pointing sticks'),
  ('watch', 'Watch', 'Dreams about watches, checking time, or broken timepieces'),
  ('wheel', 'Wheel', 'Dreams about wheels, spinning wheels, or vehicle wheels'),
  ('whip', 'Whip', 'Dreams featuring whips, being whipped, or cracking whips'),
  ('wine', 'Wine', 'Dreams featuring wine, drinking alcohol, or wine cellars'),
  ('wing', 'Wing', 'Dreams about wings, flying creatures, or growing wings'),
  ('wire', 'Wire', 'Dreams featuring wires, electrical cords, or wire fences'),
  ('wood', 'Wood', 'Dreams about wooden objects, forests, or lumber'),
  ('word', 'Word', 'Dreams featuring words, written text, or spoken language'),
  ('wreath', 'Wreath', 'Dreams featuring wreaths, circular decorations, or funeral wreaths'),
  ('zero', 'Zero', 'Dreams about the number zero, nothingness, or empty scores'),
  
  -- People/Roles
  ('baby', 'Babies', 'Dreams about infants, newborns, or new beginnings'),
  ('child', 'Children', 'Dreams about children or childhood'),
  ('elder', 'Elderly', 'Dreams about old people, wisdom, or aging'),
  ('teacher', 'Teachers', 'Dreams about instructors, mentors, or authority figures'),
  ('doctor', 'Doctors', 'Dreams about physicians, healers, or medical professionals'),
  ('police', 'Police', 'Dreams about law enforcement or authority'),
  ('celebrity', 'Celebrities', 'Dreams about famous people or public figures'),
  ('twin', 'Twins', 'Dreams about doubles, twins, or doppelgangers'),
  ('adult', 'Adult', 'Dreams about adulthood, maturity, or grown-up responsibilities'),
  ('boy', 'Boy', 'Dreams about boys, masculine youth, innocence, or immature aspects'),
  ('brother', 'Brother', 'Dreams about brothers, masculine relationships, rivalry, or support'),
  ('daughter', 'Daughter', 'Dreams about daughters, feminine aspects, legacy, or responsibilities'),
  ('father', 'Father', 'Dreams featuring your father, father figures, or paternal relationships'),
  ('girl', 'Girl', 'Dreams featuring young girls, daughters, or female children'),
  ('guard', 'Guard', 'Dreams featuring security guards, sentries, or protective figures'),
  ('guest', 'Guest', 'Dreams about visitors arriving, hosting guests, or being a guest'),
  ('hero', 'Hero', 'Dreams about heroic figures, superheroes, or acts of bravery'),
  ('hunter', 'Hunter', 'Dreams about hunters tracking prey, hunting expeditions, or being hunted'),
  ('infant', 'Infant', 'Dreams featuring newborn babies, infants crying, or baby care'),
  ('judge', 'Judge', 'Dreams featuring judges in courtrooms, verdicts, or legal proceedings'),
  ('king', 'King', 'Dreams featuring kings, royal courts, or monarchs on thrones'),
  ('knight', 'Knight', 'Dreams about armored knights, medieval warriors, or chivalry'),
  ('leader', 'Leader', 'Dreams about leaders, being in charge, or following authority figures'),
  ('man', 'Man', 'Dreams about unknown men, male figures, or masculine presence'),
  ('mother', 'Mother', 'Dreams featuring your mother, maternal figures, or motherhood'),
  ('neighbor', 'Neighbor', 'Dreams featuring neighbors, neighborhood events, or next-door activities'),
  ('nurse', 'Nurse', 'Dreams about nurses, medical care, or hospital staff'),
  ('orphan', 'Orphan', 'Dreams about orphaned children, orphanages, or abandonment'),
  ('parent', 'Parent', 'Dreams featuring parents, parental figures, or parenting'),
  ('patient', 'Patient', 'Dreams about being a patient, hospital stays, or medical examinations'),
  ('people', 'People', 'Dreams featuring crowds of people, gatherings, or unknown faces'),
  ('person', 'Person', 'Dreams about specific individuals, strangers, or unidentified people'),
  ('priest', 'Priest', 'Dreams featuring priests, clergy, or religious figures'),
  ('prince', 'Prince', 'Dreams about princes, royal sons, or fairy tale characters'),
  ('princess', 'Princess', 'Dreams featuring princesses, royal daughters, or tiaras'),
  ('queen', 'Queen', 'Dreams about queens, female monarchs, or royal courts'),
  ('ruler', 'Ruler', 'Dreams about rulers, measuring tools, or sovereign leaders'),
  ('sage', 'Sage', 'Dreams about wise sages, herbs, or spiritual advisors'),
  ('servant', 'Servant', 'Dreams featuring servants, maids, or service staff'),
  ('sibling', 'Sibling', 'Dreams about brothers and sisters, sibling rivalry, or family dynamics'),
  ('singer', 'Singer', 'Dreams featuring singers, vocal performances, or singing'),
  ('sister', 'Sister', 'Dreams about sisters, sisterly relationships, or female siblings'),
  ('slave', 'Slave', 'Dreams about slavery, being enslaved, or forced labor'),
  ('son', 'Son', 'Dreams featuring sons, male children, or father-son relationships'),
  ('student', 'Student', 'Dreams about being a student, studying, or school life'),
  ('tailor', 'Tailor', 'Dreams featuring tailors, clothing alterations, or sewing'),
  ('uncle', 'Uncle', 'Dreams featuring uncles, male relatives, or family gatherings'),
  ('victim', 'Victim', 'Dreams about being a victim, witnessing victims, or crime scenes'),
  ('visitor', 'Visitor', 'Dreams featuring visitors, guests arriving, or unexpected company'),
  ('waiter', 'Waiter', 'Dreams about waiters, restaurant service, or being served'),
  ('witness', 'Witness', 'Dreams about witnessing events, being a witness, or testimony'),
  ('woman', 'Woman', 'Dreams featuring women, female figures, or feminine presence'),
  ('writer', 'Writer', 'Dreams about writers, writing books, or being an author'),
  ('youth', 'Youth', 'Dreams about youth, young people, or being young again'),
  
  -- Time/Temporal
  ('past', 'Past', 'Dreams about past events, memories, or nostalgia'),
  ('future', 'Future', 'Dreams about future events or time travel'),
  ('apocalypse', 'Apocalypse', 'Dreams about the end of the world or civilization'),
  ('time_loop', 'Time Loop', 'Dreams about repeating events or being stuck in time'),
  ('dawn', 'Dawn', 'Dreams about dawn, new beginnings, hope, or enlightenment'),
  ('evening', 'Evening', 'Dreams set during dusk, twilight, or the end of the day'),
  ('midnight', 'Midnight', 'Dreams occurring at midnight, clock striking twelve, or darkest hour'),
  ('morning', 'Morning', 'Dreams set at dawn, waking up, or morning routines'),
  ('noon', 'Noon', 'Dreams occurring at midday, bright sunlight, or lunch time'),
  ('time', 'Time', 'Dreams about time passing, clocks, or running out of time'),
  ('twilight', 'Twilight', 'Dreams set during twilight hours, dusk, or dawn breaking'),
  ('year', 'Year', 'Dreams about years passing, New Year, or annual events'),
  
  -- Lucid/Special
  ('lucid', 'Lucid Dreaming', 'Dreams where you realize you are dreaming'),
  ('recurring', 'Recurring', 'Dreams that repeat with similar themes or scenes'),
  ('prophetic', 'Prophetic', 'Dreams that seem to predict future events'),
  ('nightmare', 'Nightmares', 'Intensely frightening or disturbing dreams'),
  ('sleep_paralysis', 'Sleep Paralysis', 'Dreams involving inability to move upon waking'),
  ('false_awakening', 'False Awakening', 'Dreams about waking up while still dreaming'),
  
  -- Elements/Materials
  ('air', 'Air', 'Dreams about air, breath, atmosphere, or the need to breathe'),
  ('earth', 'Earth', 'Dreams about earth, grounding, stability, or global concerns'),
  ('comet', 'Comet', 'Dreams about comets, rare events, cosmic messages, or fleeting opportunities'),
  ('eclipse', 'Eclipse', 'Dreams about eclipses, overshadowing, hidden aspects, or cosmic events'),
  ('land', 'Land', 'Dreams about landscapes, territories, or arriving on shore'),
  ('planet', 'Planet', 'Dreams featuring other planets, space travel, or alien worlds'),
  ('universe', 'Universe', 'Dreams about the universe, cosmos, or vast expanses of space'),
  
  -- Actions/States
  ('birth', 'Birth', 'Dreams about birth, new beginnings, creativity, or bringing ideas to life'),
  ('chase', 'Chase', 'Dreams about chasing or being chased, pursuit of goals, or avoiding fears'),
  ('clown', 'Clown', 'Dreams about clowns, hidden feelings, false happiness, or fear of ridicule'),
  ('crash', 'Crash', 'Dreams about crashes, loss of control, collision of ideas, or failure'),
  ('creature', 'Creature', 'Dreams about unknown creatures, fears, or undiscovered parts of self'),
  ('crowd', 'Crowd', 'Dreams about crowds, conformity, social anxiety, or losing individuality'),
  ('dance', 'Dance', 'Dreams about dancing, self-expression, harmony, or life rhythm'),
  ('darkness', 'Darkness', 'Dreams about darkness, the unknown, fear, or unconscious mind'),
  ('dream', 'Dream', 'Dreams about dreaming, awareness, layers of consciousness, or illusion'),
  ('fall', 'Fall', 'Dreams where you fall from heights, trip, or lose your footing'),
  ('feast', 'Feast', 'Dreams about banquets, large meals, or abundant food spreads'),
  ('game', 'Game', 'Dreams about playing games, sports, or competitive activities'),
  ('giant', 'Giant', 'Dreams about enormous people, oversized objects, or feeling tiny'),
  ('hide', 'Hide', 'Dreams about hiding from someone or something'),
  ('memory', 'Memory', 'Dreams about remembering past events, amnesia, or forgotten details'),
  ('mystery', 'Mystery', 'Dreams about solving mysteries, unknown secrets, or mysterious figures'),
  ('name', 'Name', 'Dreams about forgetting names, being called by name, or name changes'),
  ('nation', 'Nation', 'Dreams about countries, national events, or patriotic themes'),
  ('news', 'News', 'Dreams about hearing news, watching broadcasts, or breaking stories'),
  ('parade', 'Parade', 'Dreams about parades, marching bands, or festive processions'),
  ('party', 'Party', 'Dreams about parties, celebrations, or social gatherings'),
  ('plan', 'Plan', 'Dreams about making plans, blueprints, or scheming'),
  ('power', 'Power', 'Dreams about having powers, electricity, or feeling powerful'),
  ('prayer', 'Prayer', 'Dreams about praying, religious ceremonies, or spiritual practices'),
  ('quest', 'Quest', 'Dreams about going on quests, searching for something, or adventures'),
  ('question', 'Question', 'Dreams about being questioned, asking questions, or unanswered queries'),
  ('refuge', 'Refuge', 'Dreams about finding refuge, safe havens, or shelters'),
  ('rescue', 'Rescue', 'Dreams about rescuing someone, being rescued, or emergency situations'),
  ('riddle', 'Riddle', 'Dreams about solving riddles, puzzling questions, or mysteries'),
  ('sacrifice', 'Sacrifice', 'Dreams about making sacrifices, ritual offerings, or giving up something'),
  ('scene', 'Scene', 'Dreams about dramatic scenes, settings, or witnessed events'),
  ('search', 'Search', 'Dreams about searching for something, looking for lost items, or quests'),
  ('secret', 'Secret', 'Dreams about keeping secrets, discovering secrets, or hidden knowledge'),
  ('silence', 'Silence', 'Dreams characterized by complete silence, muted sounds, or inability to speak'),
  ('sleep', 'Sleep', 'Dreams about sleeping, watching others sleep, or sleep disturbances'),
  ('speech', 'Speech', 'Dreams about giving speeches, public speaking, or losing speech'),
  ('spiral', 'Spiral', 'Dreams featuring spirals, spinning motions, or spiral staircases'),
  ('story', 'Story', 'Dreams about telling stories, hearing tales, or book narratives'),
  ('trade', 'Trade', 'Dreams about trading, exchanges, or business deals'),
  ('trial', 'Trial', 'Dreams about court trials, being judged, or legal proceedings'),
  ('tribe', 'Tribe', 'Dreams featuring tribes, tribal people, or group belonging'),
  ('trick', 'Trick', 'Dreams about tricks, deception, or magic tricks'),
  ('trouble', 'Trouble', 'Dreams about being in trouble, causing problems, or difficulties'),
  ('truth', 'Truth', 'Dreams about revealing truth, confessions, or discovering facts'),
  ('turn', 'Turn', 'Dreams about turning, making turns, or changing direction'),
  ('vacation', 'Vacation', 'Dreams about vacations, holidays, or travel destinations'),
  ('virgin', 'Virgin', 'Dreams about virginity, purity, or untouched states'),
  ('vision', 'Vision', 'Dreams about visions, prophetic sights, or seeing clearly'),
  ('voice', 'Voice', 'Dreams about voices, hearing voices, or losing your voice'),
  ('warning', 'Warning', 'Dreams featuring warnings, alarm signals, or cautionary signs'),
  ('whisper', 'Whisper', 'Dreams about whispering, hushed voices, or secrets being whispered'),
  ('wisdom', 'Wisdom', 'Dreams about wise figures, gaining wisdom, or ancient knowledge'),
  ('wish', 'Wish', 'Dreams about making wishes, wish fulfillment, or magic wishes'),
  ('world', 'World', 'Dreams about the world, global events, or planet Earth'),
  ('wreck', 'Wreck', 'Dreams about wrecks, crashes, or destroyed vehicles'),
  ('zone', 'Zone', 'Dreams about zones, restricted areas, or specific regions'),
  ('pet', 'Pet', 'Dreams featuring pets, domestic animals, or caring for animals'),
  ('language', 'Language', 'Dreams about speaking foreign languages, inability to communicate, or strange words'),
  ('trumpet', 'Trumpet', 'Dreams about trumpets, brass instruments, or fanfares')
ON CONFLICT (code) DO UPDATE SET
  label = EXCLUDED.label,
  description = EXCLUDED.description;